//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DokumentaPasos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InformacijeOPasosu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InformacijeOPasosu()
        {
            this.Pasos = new HashSet<Paso>();
        }
    
        public int InformacijeOPasosuID { get; set; }
        public string Email { get; set; }
        public int Telefon { get; set; }
        public int IzdavanjePasosaID { get; set; }
        public int ProduzetakPasosaID { get; set; }
    
        public virtual IzdavanjePasosa IzdavanjePasosa { get; set; }
        public virtual ProduzetakPasosa ProduzetakPasosa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Paso> Pasos { get; set; }
    }
}
