//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DokumentaPasos.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class IzgubljenPaso
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IzgubljenPaso()
        {
            this.Pasos = new HashSet<Paso>();
        }
        [Key]
        public int IzgubljenPasosID { get; set; }

        [Required(ErrorMessage = "Please your prijava nestanka")]
        [Display(Name = "Prijava Nestanka")]
        public string PrijavaNestanka { get; set; }

        [Required(ErrorMessage = "Please your nevazeca isprava")]
        [Display(Name = "Nevazeca Isprava")]
        public string NevazecaIsprava { get; set; }

        [Required(ErrorMessage = "Please your vadi novi pasos")]
        [Display(Name = "Vadi Novi Pasos")]
        public string VadiNoviPasos { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Paso> Pasos { get; set; }
    }
}
