//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DokumentaPasos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaloletnoLouse
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MaloletnoLouse()
        {
            this.Gradjanins = new HashSet<Gradjanin>();
            this.Pasos = new HashSet<Paso>();
        }
    
        public int MaloletnoLiceID { get; set; }
        public string UverenjeODrzavljanstvu { get; set; }
        public string IzvodMaticneKnjigeRodjenih { get; set; }
        public string UplaceneNaknade { get; set; }
        public string SaglasnostRoditelja { get; set; }
        public string Fotografija { get; set; }
        public string RokVazenja { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gradjanin> Gradjanins { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Paso> Pasos { get; set; }
    }
}
