//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DokumentaPasos.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LicnaDokumentaPasosEntities : DbContext
    {
        public LicnaDokumentaPasosEntities()
            : base("name=LicnaDokumentaPasosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Gradjanin> Gradjanins { get; set; }
        public virtual DbSet<InformacijeOPasosu> InformacijeOPasosus { get; set; }
        public virtual DbSet<IzdavanjePasosa> IzdavanjePasosas { get; set; }
        public virtual DbSet<IzgubljenPaso> IzgubljenPasos { get; set; }
        public virtual DbSet<MaloletnoLouse> MaloletnoLice { get; set; }
        public virtual DbSet<Paso> Pasos { get; set; }
        public virtual DbSet<ProduzetakPasosa> ProduzetakPasosas { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Uplata> Uplatas { get; set; }
        public virtual DbSet<vwGradjanin> vwGradjanins { get; set; }
        public virtual DbSet<vwInformacijeOPasosu> vwInformacijeOPasosus { get; set; }
        public virtual DbSet<vwIzdavanjePasosa> vwIzdavanjePasosas { get; set; }
        public virtual DbSet<vwIzgubljenPaso> vwIzgubljenPasos { get; set; }
        public virtual DbSet<vwMaloletnoLouse> vwMaloletnoLice { get; set; }
        public virtual DbSet<vwPaso> vwPasos { get; set; }
        public virtual DbSet<vwProduzetakPasosa> vwProduzetakPasosas { get; set; }
        public virtual DbSet<vwUplata> vwUplatas { get; set; }
    }
}
