//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DokumentaPasos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paso
    {
        public int PasosID { get; set; }
        public string IzdajePU { get; set; }
        public string Drzava { get; set; }
        public int Telefon { get; set; }
        public int InformacijeOPasosuID { get; set; }
        public int UplataID { get; set; }
        public int GradjaninID { get; set; }
        public int MaloletnoLiceID { get; set; }
        public int IzgubljenPasosID { get; set; }
    
        public virtual Gradjanin Gradjanin { get; set; }
        public virtual InformacijeOPasosu InformacijeOPasosu { get; set; }
        public virtual IzgubljenPaso IzgubljenPaso { get; set; }
        public virtual MaloletnoLouse MaloletnoLouse { get; set; }
        public virtual Uplata Uplata { get; set; }
    }
}
