//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DokumentaPasos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProduzetakPasosa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProduzetakPasosa()
        {
            this.InformacijeOPasosus = new HashSet<InformacijeOPasosu>();
        }
    
        public int ProduzetekPasosaID { get; set; }
        public string LicnaKarta { get; set; }
        public string StariPasos { get; set; }
        public string TroskoviUplate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InformacijeOPasosu> InformacijeOPasosus { get; set; }
    }
}
