//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DokumentaPasos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwGradjanin
    {
        public int GradjaninID { get; set; }
        public string Tip { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public string JMBG { get; set; }
        public string Pol { get; set; }
        public Nullable<System.DateTime> DatumIzdavanja { get; set; }
        public Nullable<System.DateTime> DatumRodjenja { get; set; }
        public string MestoRodjenja { get; set; }
        public string Prebivaliste { get; set; }
        public string KodDrzave { get; set; }
        public int MaloletnoLiceID { get; set; }
        public string VaziDo { get; set; }
        public int Expr1 { get; set; }
        public string UverenjeODrzavljanstvu { get; set; }
        public string IzvodMaticneKnjigeRodjenih { get; set; }
        public string UplaceneNaknade { get; set; }
        public string SaglasnostRoditelja { get; set; }
        public string Fotografija { get; set; }
        public string RokVazenja { get; set; }
    }
}
