//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DokumentaPasos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwInformacijeOPasosu
    {
        public int InformacijeOPasosuID { get; set; }
        public string Email { get; set; }
        public int Telefon { get; set; }
        public int IzdavanjePasosaID { get; set; }
        public int ProduzetakPasosaID { get; set; }
        public string LicnaKarta { get; set; }
        public string IzvodMaticneKnjigeRodjenih { get; set; }
        public string StariPasos { get; set; }
        public string TroskoviUplate { get; set; }
    }
}
