//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DokumentaPasos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwIzgubljenPaso
    {
        public int IzgubljenPasosID { get; set; }
        public string PrijavaNestanka { get; set; }
        public string NevazecaIsprava { get; set; }
        public string VadiNoviPasos { get; set; }
    }
}
