//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DokumentaPasos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwUplata
    {
        public int UplataID { get; set; }
        public string ObrzacPutneIsprave { get; set; }
        public string AdministrativnaTaksa { get; set; }
    }
}
